- name: Install Avahi system packages.
  apt: pkg={{item}} state=installed #update-cache=yes
  with_items:
    - avahi-daemon
    - libnss-mdns
  sudo: yes

- name: Configuring Avahi to use mdns
  lineinfile: 'dest=/etc/nsswitch.conf regexp="^hosts\:" line="hosts:      files mdns4_minimal [NOTFOUND=return] dns mdns4 mdns"'
  sudo: yes
  notify:
    - restart avahi

- name: Configuring Avahi to advertize SMB
  template: src=smb.service.template dest=/etc/avahi/services/smb.service
  sudo: yes
  when: samba is defined
  notify:
    - restart avahi

