- hosts: localhost

  tasks:
    - name: Creating OVPN folder
      file: state=directory path={{ openvpn_folder }} mode=0700
      sudo: yes

    - name: Checking if OVPN config exists
      stat: path={{ openvpn_folder }}/openvpn.conf
      register: openvpn_conf_stat

    - name: Checking if OVPN CA exists
      stat: path={{ openvpn_folder }}/pki/ca.crt
      register: openvpn_ca_stat

    - name: Failing if the config is not complete yet
      fail: msg="CA authority is not created yet. Type 'ovpn/create_ca.sh' to do it and update the service after that"
      when: not openvpn_ca_stat.stat.exists or not openvpn_conf_stat.stat.exists

    - name: Install OVPN Containers
      docker:
        name: openvpn
        image: kylemanna/openvpn
        state: started
        pull: always
        restart_policy: always
        expose: # <----- SHAME TO ANSIBLE!!!!
          - 1194
        ports:
          - 1194:1194
        volumes:
          - "{{ openvpn_folder }}/:/etc/openvpn/"
      sudo: yes
