#- name: checking if docker installed
#  command: which docker
#  register: docker-installed
#
#- name: Installing Docker
#  command: "wget -qO- https://get.docker.com/ | sh"
#  sudo: yes3


#- name: Installing prerequisites
#  apt: pkg={{item}}
#  sudo: yes
#  with_items:
#    - wget
#  tags:
#    - docker
#
#- name: Checking is docker exists
#  stat: path=/usr/bin/docker
#  register: docker_stat
#  tags:
#    - docker
#
#- name: Installing docker from source
#  command: curl -sSL https://get.docker.com/ | sh
#  when: not docker_stat.stat.exists
#  sudo: yes
#  tags:
#    - docker

- name: Adding Docker repo key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=36A1D7869245C8950F966E92D8576A8BA88D21E9
  sudo: yes
  tags:
    - docker

- name: Add the Docker PPA
  command: >
    sh -c "echo deb https://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
    && apt-get update
  args:
    creates: /etc/apt/sources.list.d/docker.list
  sudo: yes
  tags:
    - docker

- name: Install Docker
  apt: pkg=lxc-docker
  sudo: yes
  tags:
    - docker

- name: Install Python Setuptools
  apt: pkg=python-setuptools
  sudo: yes
  tags:
    - docker

- name: Installing pip
  easy_install: name=pip
  sudo: yes
  tags:
    - docker

- name: Install docker-py
  pip: name=docker-py==1.1.0
  sudo: yes
  tags:
    - docker

